server:
  port: 8083
  servlet:
    context-path: /tourism-website-service
spring:
  datasource:
    username: ${OFFICAL_MYSQL_USERNAME}
    password: ${OFFICAL_MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${OFFICAL_MYSQL_HOST}:${OFFICAL_MYSQL_PORT}/EASTBABEL_CUL?useUnicode=true&characterEncoding=UTF-8&verifyServerCertificate=false&serverTimezone=GMT%2B8&useSSL=false&allowMultiQueries=true
    type: com.alibaba.druid.pool.DruidDataSource
    druid:
      initial-size: 5 #初始化时建立物理连接的个数
      min-idle: 5 #最小连接池数量
      max-active: 10 #最大连接池数量
      max-wait: 60000 #获取连接时最大等待时间
      connection-init-sqls: set names utf8mb4
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    database-platform: org.hibernate.dialect.MySQLDialect
  application:
    name: OFFICAL
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mail:
    #smtp服务主机  qq邮箱则为smtp.qq.com
    host: smtp.feishu.cn
    #服务协议
    protocol: smtps
    # 编码集
    default-encoding: UTF-8
    #发送邮件的账户
    username: offical@eastbabel.cn
    #授权码
    password: FURDzdJEYd3M0FmK
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
token:
  salt:
    admin:
      auth: 0463c4c19d154a84a8e9d2e5d4ffe90e
      refresh: 3231c083da13413b930ebfab41b71021
qiniu:
  ak: c-mzyuLiU647Y0LZMZ4x1QLIxQk3oUERyso0xdik
  sk: ZPlu5pGLOeIdP5AUzxlg0Hx4kphVxdvOOgAdiT3Z
  bucketname: eastbabel-data
  domain: http://qxo1gxby1.hb-bkt.clouddn.com/